[package]
name = "rust-test-ios"
version = "0.1.0"
authors = ["Steven Sheldon"]

[dependencies]
regex = "0.1"
serde_json = "0.7"
walkdir = "0.1"

[dependencies.toml]
version = "0.1"
default-features = false
features = ["serde"]
